"""Add registration slip model and payment fields

Revision ID: 073dfb8e0ce3
Revises: 788a8e5c1bef
Create Date: 2025-10-09 12:18:08.302826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073dfb8e0ce3'
down_revision = '788a8e5c1bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_number', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.DateTime(), nullable=False),
    sa.Column('pdf_filename', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slip_number')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('reference', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('reference')
        batch_op.drop_column('method')
        batch_op.drop_column('amount')
        batch_op.drop_column('approved_date')

    op.drop_table('registration_slip')
    # ### end Alembic commands ###
