"""Update models with improved relationships

Revision ID: 66841a9d04f8
Revises: 073dfb8e0ce3
Create Date: 2025-10-09 13:53:45.146777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66841a9d04f8'
down_revision = '073dfb8e0ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_image', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_payment_reference', ['reference'])  # FIXED: Added constraint name

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=True))

    with op.batch_alter_table('registration_slip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('program_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faculty_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('faculty')

    with op.batch_alter_table('registration_slip', schema=None) as batch_op:
        batch_op.drop_column('faculty_name')
        batch_op.drop_column('program_name')
        batch_op.drop_column('semester')
        batch_op.drop_column('academic_year')

    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_column('academic_year')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payment_reference', type_='unique')  # FIXED: Added constraint name
        batch_op.drop_column('receipt_image')

    op.drop_table('system_log')
    # ### end Alembic commands ###